name: PHP CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: |
        if [ -f "./composer.json" ]; then
          composer validate --strict
        else
          echo "composer.json not found, skipping validation"
        fi

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        if [ -f "./composer.json" ]; then
          composer install --prefer-dist --no-progress
        else
          echo "composer.json not found, skipping installation"
        fi

    - name: PHP Syntax Check
      run: |
        if [ -d "./src" ]; then
          find ./src -name "*.php" -print0 | xargs -0 -n1 php -l
        fi
        if [ -d "./test" ]; then
          find ./test -name "*.php" -print0 | xargs -0 -n1 php -l
        fi
        if [ -d "./examples" ]; then
          find ./examples -name "*.php" -print0 | xargs -0 -n1 php -l
        fi

    - name: PHP Code Sniffer
      run: |
        if [ -f "./vendor/bin/phpcs" ]; then
          ./vendor/bin/phpcs --standard=PSR12 src
        else
          echo "PHP_CodeSniffer not installed, skipping code style check"
        fi

    - name: PHPUnit Tests
      run: |
        if [ -f "./vendor/bin/phpunit" ]; then
          ./vendor/bin/phpunit
        else
          echo "PHPUnit not installed, skipping tests"
        fi 